<?php
/**
 * Portal Tela Theme Functions
 */

// Theme setup
add_action('after_setup_theme', 'portal_tela_setup');

function portal_tela_setup()
{
    // Add language support
    load_theme_textdomain('portal-tela-theme', get_template_directory() . '/languages');

    // Add theme support
    add_theme_support('automatic-feed-links');
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('html5', array('search-form', 'comment-form', 'comment-list', 'gallery', 'caption'));
    add_theme_support('custom-background');
    add_theme_support('custom-header');

    // Register navigation menus
    register_nav_menus(array(
        'primary' => __('Primary Menu', 'portal-tela-theme'),
        'secondary' => __('Secondary Menu', 'portal-tela-theme'),
        'footer' => __('Footer Menu', 'portal-tela-theme'),
    ));
}

// Enqueue styles and scripts
add_action('wp_enqueue_scripts', 'portal_tela_enqueue_assets');

function portal_tela_enqueue_assets()
{
    // Get asset manifest (generated by Vite)
    $assets_dir = get_template_directory() . '/assets';

    // Enqueue main style
    if (file_exists($assets_dir . '/css/main.css')) {
        wp_enqueue_style(
            'portal-tela-main',
            get_template_directory_uri() . '/assets/css/main.css',
            array(),
            filemtime($assets_dir . '/css/main.css')
        );
    }

    // Enqueue main script
    if (file_exists($assets_dir . '/js/main.js')) {
        wp_enqueue_script(
            'portal-tela-main',
            get_template_directory_uri() . '/assets/js/main.js',
            array(),
            filemtime($assets_dir . '/js/main.js'),
            true
        );
    }

    // Remove emoji styles and scripts
    remove_action('wp_head', 'print_emoji_detection_script', 7);
    remove_action('wp_print_styles', 'print_emoji_styles');

}

// Register sidebars/widgets
add_action('widgets_init', 'portal_tela_register_sidebars');

function portal_tela_register_sidebars()
{
    register_sidebar(array(
        'name' => __('Primary Sidebar', 'portal-tela-theme'),
        'id' => 'primary-sidebar',
        'description' => __('Main sidebar for blog posts', 'portal-tela-theme'),
        'before_widget' => '<div id="%1$s" class="widget %2$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3 class="widget-title">',
        'after_title' => '</h3>',
    ));

    register_sidebar(array(
        'name' => __('Footer Widgets', 'portal-tela-theme'),
        'id' => 'footer-widgets',
        'description' => __('Widgets displayed in footer', 'portal-tela-theme'),
        'before_widget' => '<div id="%1$s" class="footer-widget %2$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3>',
        'after_title' => '</h3>',
    ));
}

// Custom excerpt length
add_filter('excerpt_length', function () {
    return 20;
});

// Custom excerpt ellipsis
add_filter('excerpt_more', function () {
    return ' [...]';
});

// Remove p tags from images
add_filter('the_content', function ($content) {
    return preg_replace('/<p>\s*(<a .*?><img.*?><\/a>|<img.*?>)\s*<\/p>/iU', '\1', $content);
});

// Add custom image sizes
add_image_size('post-thumbnail-large', 1200, 675, true);
add_image_size('post-thumbnail-medium', 800, 450, true);
add_image_size('post-thumbnail-small', 400, 225, true);

// Customize WordPress admin
add_action('admin_head', 'portal_tela_admin_style');

function portal_tela_admin_style()
{
    echo '<!-- Portal Tela Theme -->';
}

// Clean up WordPress head
remove_action('wp_head', 'wp_generator');
remove_action('wp_head', 'wlwmanifest_link');
remove_action('wp_head', 'rsd_link');
remove_action('wp_head', 'wp_shortlink');

// Add custom body classes
add_filter('body_class', function ($classes) {
    if (is_home()) {
        $classes[] = 'is-home';
    }

    if (is_single()) {
        $classes[] = 'is-single-post';
    }

    return $classes;
});

// Content generator integration
add_filter('the_content', 'portal_tela_add_content_generator_meta');

function portal_tela_add_content_generator_meta($content)
{
    if (is_single() && !is_admin()) {
        $generator_id = get_post_meta(get_the_ID(), '_content_generator_id', true);
        $source_url = get_post_meta(get_the_ID(), '_content_generator_source_url', true);

        if ($generator_id || $source_url) {
            $notice = '<div class="content-generator-notice card mt-4 p-3"><small class="text-muted">';
            $notice .= '🤖 Este conteúdo foi gerado por IA';
            if ($source_url) {
                $notice .= ' baseado em <a href="' . esc_url($source_url) . '" target="_blank">fonte original</a>';
            }
            $notice .= '</small></div>';
            $content .= $notice;
        }
    }

    return $content;
}

// Add custom post type support (optional)
add_filter('use_block_editor_for_post_type', function ($use_block_editor, $post_type) {
    // Allow block editor for posts
    return true;
}, 10, 2);
