<?php
/**
 * Plugin Name: Content Generator
 * Plugin URI: https://github.com/KhaiDreams/teste-tecnico-portal-tela
 * Description: Receive and publish content generated by AI from external service
 * Version: 1.0.0
 * Author: Portal Tela
 * Author URI: https://portaltela.com
 * License: MIT
 * Requires at least: 6.0
 * Requires PHP: 8.0
 * Text Domain: content-generator
 * Domain Path: /languages
 */

if (!defined('ABSPATH')) {
    exit;
}

define('CONTENT_GENERATOR_PLUGIN_DIR', plugin_dir_path(__FILE__));
define('CONTENT_GENERATOR_PLUGIN_URL', plugin_dir_url(__FILE__));
define('CONTENT_GENERATOR_VERSION', '1.0.0');

// Include required files
require_once CONTENT_GENERATOR_PLUGIN_DIR . 'includes/class-webhook.php';
require_once CONTENT_GENERATOR_PLUGIN_DIR . 'includes/class-post-creator.php';
require_once CONTENT_GENERATOR_PLUGIN_DIR . 'includes/class-validator.php';

// Hook to initialize plugin
add_action('plugins_loaded', 'content_generator_init');

function content_generator_init()
{
    // Register REST endpoint only when REST API is initialized.
    add_action('rest_api_init', array('ContentGenerator\\Webhook', 'register_routes'));
}

// Plugin activation hook
register_activation_hook(__FILE__, 'content_generator_activate');

function content_generator_activate()
{
    // Create options if they don't exist
    if (!get_option('content_generator_webhook_secret')) {
        update_option('content_generator_webhook_secret', wp_generate_password(32, true, true));
    }

    flush_rewrite_rules();
}

// Plugin deactivation hook
register_deactivation_hook(__FILE__, 'content_generator_deactivate');

function content_generator_deactivate()
{
    flush_rewrite_rules();
}

// Load plugin text domain
add_action('plugins_loaded', function () {
    load_plugin_textdomain(
        'content-generator',
        false,
        dirname(plugin_basename(__FILE__)) . '/languages'
    );
});
